name: DocFx
on: workflow_dispatch
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core 2.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'
    - name: Setup .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: DocFx.AspNetCore.ServerSentEvents/wwwroot